version: '3.2'

services:
  api:
    image: adsboard.api
    container_name: api
    build: 
      context: ../../
      dockerfile: ./Adsboard.Api/Dockerfile
    ports:
      - 5100:5100
      - 5000:5000
    networks:
      - adsboard.network

  identity-service:
    image: adsboard.services.identity
    container_name: identity-service
    build: 
      context: ../../
      dockerfile: ./Adsboard.Services.Identity/Dockerfile
    ports:
      - 5101:5101
      - 5001:5001
    networks:
      - adsboard.network

  users-service:
    image: adsboard.services.users
    container_name: users-service
    build: 
      context: ../../
      dockerfile: ./Adsboard.Services.Users/Dockerfile
    ports:
      - 5102:5102
      - 5002:5002
    networks:
      - adsboard.network

  operations-service:
    image: adsboard.services.operations
    container_name: operations-service
    build: 
      context: ../../
      dockerfile: ./Adsboard.Services.Operations/Dockerfile
    ports:
      - 5103:5103
      - 5003:5003
    networks:
      - adsboard.network

  adverts-service:
    image: adsboard.services.adverts
    container_name: adverts-service
    build: 
      context: ../../
      dockerfile: ./Adsboard.Services.Adverts/Dockerfile
    ports:
      - 5104:5104
      - 5004:5004
    networks:
      - adsboard.network

  categories-service:
    image: adsboard.services.categories
    container_name: categories-service
    build: 
      context: ../../
      dockerfile: ./Adsboard.Services.Categories/Dockerfile
    ports:
      - 5105:5105
      - 5005:5005
    networks:
      - adsboard.network

networks:
  adsboard.network:
    external: true