@apiUrl = http://localhost:5000
@identityUrl = http://localhost:5001
@accessToken = xxxxxxxxxxxxxxx

### Sign up
POST {{identityUrl}}/sign-up
content-type: application/json

{
	"email": "test@testemail.com",
	"password": "test"
}

### Sign in
POST {{identityUrl}}/sign-in
content-type: application/json

{
	"email": "test@testemail.com",
	"password": "test"
}

### Get user's adverts
GET {{apiUrl}}/adverts/me
content-type: application/json
authorization: Bearer {{accessToken}}

### Get all adverts
GET {{apiUrl}}/adverts
content-type: application/json
authorization: Bearer {{accessToken}}

### Get advert by id
GET {{apiUrl}}/adverts/{advertId}
content-type: application/json
authorization: Bearer {{accessToken}}

### Archive advert with id
DELETE {{apiUrl}}/adverts/{advertId}
content-type: application/json
authorization: Bearer {{accessToken}}

### Update advert with id
PATCH {{apiUrl}}/adverts/{advertId}
content-type: application/json
authorization: Bearer {{accessToken}}

{
	"title": "New Test Title"
}

### Create advert for logged user
POST {{apiUrl}}/adverts
Content-Type: application/json
authorization: Bearer {{accessToken}}

{
    "title": "Test title",
    "description": "Testing description, description testing.",
    "categoryId": "45d93721-e11e-4bab-a030-85b926420a17"
}

### get all categories
GET {{apiUrl}}/categories
Content-Type: application/json
authorization: Bearer {{accessToken}}

### create category
POST {{apiUrl}}/categories
Content-Type: application/json
authorization: Bearer {{accessToken}}

{
    "userId": "7ecd4501-1ac4-4882-bcb9-6569de4917bf",
    "name": "Test category",
}